---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-puppet"
  download_policy: "{{ foreman_products_defaults_download_policy_puppet7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_puppet7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_puppet7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_puppet7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_puppet7 | bool }}"


foreman_products_puppet7_el7:
  - name: "{{ foreman_product_name_prefix | default('') }}Puppet"
    label: "{{ foreman_product_label_prefix | default('') }}Puppet"
    organization: "{{ foreman_organization_puppet7_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL8 - x86_64"
        label: "{{ foreman_repo_label_prefix | default('') }}puppet7-el7"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_puppet7_el7 }}/puppet7/el/8/x86_64"
        organization: "{{ foreman_organization_puppet7_el7 }}"

foreman_products_puppet7_el8:
  - name: "{{ foreman_product_name_prefix | default('') }}Puppet"
    label: "{{ foreman_product_label_prefix | default('') }}Puppet"
    organization: "{{ foreman_organization_puppet7_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL8 - x86_64"
        label: "{{ foreman_repo_label_prefix | default('') }}puppet7-el8"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_puppet7_el8 }}/puppet7/el/8/x86_64"
        organization: "{{ foreman_organization_puppet7_el8 }}"

foreman_products_puppet7_el9:
  - name: "{{ foreman_product_name_prefix | default('') }}Puppet"
    label: "{{ foreman_product_label_prefix | default('') }}Puppet"
    organization: "{{ foreman_organization_puppet7_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL9 - x86_64"
        label: "{{ foreman_repo_label_prefix | default('') }}puppet7-el9"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_puppet7_el9 }}/puppet7/el/9/x86_64"
        organization: "{{ foreman_organization_puppet7_el9 }}"

foreman_products_puppet7_main: []
foreman_products_puppet7: "{{ ( foreman_products_puppet7_main | default([]) if foreman_enable_puppet7 | bool else [] ) |
  union( foreman_products_puppet7_el7 | default([]) if foreman_enable_puppet7_el7 | bool else [] ) |
  union( foreman_products_puppet7_el8 | default([]) if foreman_enable_puppet7_el8 | bool else [] ) |
  union( foreman_products_puppet7_el9 | default([]) if foreman_enable_puppet7_el9 | bool else [] )
  }}"


foreman_content_views_puppet7_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}puppet7_el7"
    organization: "{{ foreman_organization_puppet7_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL7 - x86_64"
        product: "{{ foreman_product_name_prefix | default('') }}Puppet"
    allow_promote: "{{ foreman_cv_allow_promote_puppet7_el7 }}"

foreman_content_views_puppet7_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}puppet7_el8"
    organization: "{{ foreman_organization_puppet7_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL8 - x86_64"
        product: "{{ foreman_product_name_prefix | default('') }}Puppet"
    allow_promote: "{{ foreman_cv_allow_promote_puppet7_el8 }}"

foreman_content_views_puppet7_el9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}puppet7_el9"
    organization: "{{ foreman_organization_puppet7_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Puppet 7 Repository EL9 - x86_64"
        product: "{{ foreman_product_name_prefix | default('') }}Puppet"
    allow_promote: "{{ foreman_cv_allow_promote_puppet7_el9 }}"

foreman_content_views_puppet7_main: []
foreman_content_views_puppet7: "{{ ( foreman_content_views_puppet7_main | default([]) if foreman_enable_puppet7 | bool else [] ) |
  union( foreman_content_views_puppet7_el7 | default([]) if foreman_enable_puppet7_el7 | bool else [] ) |
  union( foreman_content_views_puppet7_el8 | default([]) if foreman_enable_puppet7_el8 | bool else [] ) |
  union( foreman_content_views_puppet7_el9 | default([]) if foreman_enable_puppet7_el9 | bool else [] )
  }}"

